"""Pydantic v2 request/response models for the API."""
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Response envelope
# ---------------------------------------------------------------------------

class APIResponse(BaseModel):
    """Standard success envelope."""
    data: Any
    warnings: list[str] = []


class ErrorDetail(BaseModel):
    code: str
    message: str
    detail: Any = None


class ErrorResponse(BaseModel):
    """Standard error envelope."""
    error: ErrorDetail


# ---------------------------------------------------------------------------
# Portfolio requests
# ---------------------------------------------------------------------------

class AddPositionRequest(BaseModel):
    ticker: str
    asset_type: Literal["stock", "btc", "eth"] = "stock"
    quantity: float = Field(gt=0)
    avg_cost: float = Field(gt=0)
    entry_date: str  # YYYY-MM-DD
    sector: str | None = None
    industry: str | None = None
    # Thesis fields (all optional -- backward compatible)
    thesis_text: str | None = None
    expected_return_pct: float | None = None  # e.g. 0.18 for 18%
    expected_hold_days: int | None = None
    target_price: float | None = None
    stop_loss: float | None = None


class ThesisResponse(BaseModel):
    """Thesis data for a position with computed drift fields."""
    thesis_id: int
    ticker: str
    expected_signal: str
    expected_confidence: float
    expected_entry_price: float
    expected_target_price: float | None = None
    expected_return_pct: float | None = None
    expected_stop_loss: float | None = None
    expected_hold_days: int | None = None
    thesis_text: str | None = None
    created_at: str | None = None
    hold_days_elapsed: int | None = None
    hold_drift_days: int | None = None
    return_drift_pct: float | None = None


class SetCashRequest(BaseModel):
    amount: float = Field(ge=0)


class ScaleRequest(BaseModel):
    multiplier: float = Field(gt=0)


class SplitRequest(BaseModel):
    ticker: str
    ratio: int = Field(gt=0)


# ---------------------------------------------------------------------------
# Backtest requests
# ---------------------------------------------------------------------------

class BacktestRequest(BaseModel):
    ticker: str
    start_date: str
    end_date: str
    asset_type: Literal["stock", "btc", "eth"] = "stock"
    initial_capital: float = 100_000.0
    rebalance_frequency: Literal["daily", "weekly", "monthly"] = "weekly"
    agents: list[str] | None = None
    position_size_pct: float = 0.10
    stop_loss_pct: float | None = 0.10
    take_profit_pct: float | None = 0.20
    buy_threshold: float = 0.30
    sell_threshold: float = -0.30


class BatchBacktestRequest(BaseModel):
    tickers: list[str] = Field(min_length=1)
    agent_combos: list[list[str]] = Field(min_length=1)
    start_date: str
    end_date: str
    initial_capital: float = 100_000.0
    position_size_pct: float = 1.0
    rebalance_frequency: Literal["daily", "weekly", "monthly"] = "weekly"
    stop_loss_pct: float | None = None
    take_profit_pct: float | None = None


# ---------------------------------------------------------------------------
# Daemon requests
# ---------------------------------------------------------------------------

class RunOnceRequest(BaseModel):
    job: Literal["daily", "weekly"]


# ---------------------------------------------------------------------------
# Summary responses
# ---------------------------------------------------------------------------

class SummaryResponse(BaseModel):
    """Weekly portfolio summary generated by Claude."""
    summary_text: str
    generated_at: str
    model: str
    input_tokens: int
    output_tokens: int
    cost_usd: float
    positions_covered: list[str]
